import { QueryProvider } from "@/components";
import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/components/providers/app-providers"; // Adjust import path
import { getLocale, getMessages } from "next-intl/server"; // Add next-intl imports

// FIXME: change Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang="en">
      <body>
        <AppProviders messages={messages} locale={locale}>
          <QueryProvider>{children}</QueryProvider>
        </AppProviders>
      </body>
    </html>
  );
}
