import { QueryProvider } from "@/components";
import { Providers } from "@/components/providers"; // Import your Providers component
import type { Metadata } from "next";
import "./globals.css";

// FIXME: change Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <QueryProvider>
        <Providers>{children}</Providers>
      </QueryProvider>
    </>
  );
}
